### PR TITLE
Fixed #44 - Handle response body with no example

### LINKED ISSUE #44: A response body with no example causes crash
Some RAML examples do not provide an "example" or "schema" for a response body.

When raml-fleece encounters this, it just crashes with:

TypeError: Cannot read property 'example' of null
    at /opt/local/lib/node_modules/raml-fleece/src/main.js:106:19
    at /opt/local/lib/node_modules/raml-fleece/node_modules/lodash/lodash.js:3579:27
    ...

### PR DESCRIPTION
**Pull request by dcrossleyau**

### CODE REVIEW

File: src/main.js [hunk 1]
```diff
@@ -103,8 +103,8 @@ function makeExamplesOf(obj) {
     }
     return {
       type: _.isString(key) ? key : undefined,
-      example: val.example,
-      schema: val.schema
+      example: val ? val.example : undefined,
```
Comment (cameron-white-janrain) [inline src/main.js]: I think `val && val.example` would also work.

Comment (dcrossleyau) [inline src/main.js]: Of course. Better. Thanks for the guidance.

**Comment by dcrossleyau** [comment]
I updated the Issue #44 with a test document.
